apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-artemis-amq-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://something
  project: default
  source:
    path: appsets
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true