apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: brokers-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jstrickl-redhat/amq-artemis-broker.git
              revision: HEAD
              files:
                - path: appset/broker-list.yaml
          - list:
              elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: '{{.project}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: '{{.repoUrl}}'
          targetRevision: HEAD
          path: 'amq-artemis-operator/{{.brokerName}}/{{.env}}'
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}'