apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: brokers-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jstrickl-redhat/amq-artemis-broker.git
              revision: HEAD
              files:
                - path: amq-broker/broker-appset/broker-group.yaml
          - list:
              elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: '{{.repoUrl}}'
          targetRevision: HEAD
          path: 'amq-broker/broker-appset/{{.brokerType}}/{{.ha}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: user1-argocd
