apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: amq-root-app
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD