apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extra-jars
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10MB